import { FamilyMember } from '../types/profiles'

const now = new Date().toISOString()

// Harris-Benedict calorie targets (rough estimates seeded as defaults)
export const SEED_FAMILY_PROFILES: FamilyMember[] = [
  {
    id: 'potter-harry',
    name: 'Harry',
    role: 'father',
    age: 58,
    weight: 102,
    height: 184,
    allergies: [],
    conditions: ['hypertension'],
    dietPreference: 'mediterranean',
    avatarEmoji: '👨',
    isSchoolAge: false,
    supplements: [
      {
        id: 'harry-sup-1',
        name: 'Lisinopril 10mg',
        dose: '10mg',
        meal: 'breakfast',
        notes: 'Blood pressure medication',
      },
    ],
    dailyCalorieTarget: 2100,
    macroTargets: { protein: 157, carbs: 236, fat: 70 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'potter-ginny',
    name: 'Ginny',
    role: 'mother',
    age: 56,
    weight: 62,
    height: 167,
    allergies: ['peanuts'],
    conditions: ['osteoporosis'],
    dietPreference: 'mediterranean',
    avatarEmoji: '👩',
    isSchoolAge: false,
    supplements: [
      {
        id: 'ginny-sup-1',
        name: 'Calcium + D3',
        dose: '1000mg / 800 IU',
        meal: 'dinner',
        notes: 'Bone health — osteoporosis management',
      },
    ],
    dailyCalorieTarget: 1700,
    macroTargets: { protein: 127, carbs: 191, fat: 57 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'potter-james',
    name: 'James',
    role: 'son',
    age: 21,
    weight: 84,
    height: 186,
    allergies: ['tree nuts'],
    conditions: [],
    dietPreference: 'none',
    avatarEmoji: '🧑',
    isSchoolAge: false,
    dailyCalorieTarget: 2600,
    macroTargets: { protein: 195, carbs: 293, fat: 87 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'potter-lily',
    name: 'Lily',
    role: 'daughter',
    age: 20,
    weight: 61,
    height: 172,
    allergies: ['dairy'],
    conditions: [],
    dietPreference: 'none',
    avatarEmoji: '👧',
    isSchoolAge: false,
    dailyCalorieTarget: 1900,
    macroTargets: { protein: 142, carbs: 214, fat: 63 },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'potter-albus',
    name: 'Albus',
    role: 'son',
    age: 18,
    weight: 79,
    height: 182,
    allergies: [],
    conditions: [],
    dietPreference: 'none',
    avatarEmoji: '🧑',
    isSchoolAge: false,
    dailyCalorieTarget: 2700,
    macroTargets: { protein: 202, carbs: 304, fat: 90 },
    createdAt: now,
    updatedAt: now,
  },
]

export const FAMILY_NAME = 'Potter'
