import { Recipe } from '../types/recipes'

const now = new Date().toISOString()

export const SEED_RECIPES: Recipe[] = [
  // ===== COCINA ESPAÑOLA =====
  {
    id: 'seed-001', name: 'Paella Valenciana', category: 'lunch', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Calienta aceite en una paellera grande a fuego medio.', 'Sofríe el pollo y el conejo hasta dorar.', 'Añade el tomate triturado y las judías verdes. Sofríe 5 minutos.', 'Incorpora el arroz y tuéstalo 2 minutos.', 'Vierte el caldo caliente (doble que el arroz) y el azafrán.', 'Cocina a fuego fuerte 10 min, luego baja el fuego 8 min más.', 'Deja reposar 5 minutos tapado antes de servir.'],
    ingredients: [
      { name: 'Arroz de grano corto', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Pollo troceado', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Judías verdes', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Tomate', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Azafrán', quantity: 1, unit: 'g', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
      { name: 'Caldo de pollo', quantity: 1200, unit: 'ml', isAllergen: false },
      { name: 'Pimentón dulce', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 20, cookTime: 40, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 520, protein: 32, carbs: 65, fat: 14, fiber: 3, sodium: 480 },
    allergens: [], tags: ['arroz', 'español', 'sin gluten'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-002', name: 'Gazpacho Andaluz', category: 'lunch', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Trocea todos los vegetales.', 'Pon los tomates, pepino, pimiento, ajo y cebolla en la batidora.', 'Añade el pan remojado, el aceite, el vinagre y la sal.', 'Tritura hasta obtener una crema fina.', 'Cuela por un colador fino.', 'Refrigera al menos 2 horas antes de servir.', 'Sirve con tropezones de pan, tomate y pepino.'],
    ingredients: [
      { name: 'Tomates maduros', quantity: 1000, unit: 'g', isAllergen: false },
      { name: 'Pepino', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Pimiento verde', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Diente de ajo', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Pan del día anterior', quantity: 80, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Aceite de oliva virgen extra', quantity: 80, unit: 'ml', isAllergen: false },
      { name: 'Vinagre de jerez', quantity: 30, unit: 'ml', isAllergen: false },
    ],
    prepTime: 15, cookTime: 0, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 180, protein: 3, carbs: 18, fat: 11, fiber: 4, sodium: 320 },
    allergens: ['gluten'], tags: ['vegetariano', 'verano', 'frío'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-003', name: 'Tortilla Española', category: 'breakfast', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Pela y corta las patatas en láminas finas.', 'Pela y pica finamente la cebolla.', 'Calienta aceite en una sartén y fríe las patatas y la cebolla a fuego medio-bajo 20 min.', 'Escurre el aceite y mezcla las patatas con los huevos batidos y sazonados.', 'En una sartén antiadherente con un poco de aceite, vierte la mezcla y cuaja 5 min.', 'Da la vuelta con un plato y cocina 3 min más.', 'Sirve caliente o a temperatura ambiente.'],
    ingredients: [
      { name: 'Huevos', quantity: 6, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Patatas', quantity: 600, unit: 'g', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 200, unit: 'ml', isAllergen: false },
      { name: 'Sal', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 15, cookTime: 30, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 340, protein: 14, carbs: 28, fat: 20, fiber: 2, sodium: 280 },
    allergens: ['eggs'], tags: ['vegetariano', 'sin gluten', 'clásico'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-004', name: 'Croquetas de Jamón', category: 'lunch', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Derrite la mantequilla en un cazo y sofríe la cebolla picada.', 'Añade la harina y tuéstala 2 minutos removiendo.', 'Incorpora la leche poco a poco sin dejar de remover hasta obtener una bechamel espesa.', 'Añade el jamón picado y sazona con sal y nuez moscada.', 'Extiende en una bandeja y deja enfriar en nevera 2 horas.', 'Forma las croquetas, pásalas por huevo y pan rallado.', 'Fríe en aceite caliente hasta dorar.'],
    ingredients: [
      { name: 'Jamón ibérico', quantity: 150, unit: 'g', isAllergen: false },
      { name: 'Leche entera', quantity: 500, unit: 'ml', isAllergen: true, allergenType: 'dairy' },
      { name: 'Mantequilla', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Harina', quantity: 80, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Huevo', quantity: 2, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Pan rallado', quantity: 100, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Nuez moscada', quantity: 1, unit: 'pizca', isAllergen: false },
    ],
    prepTime: 30, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/b7y4wt1511813681.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 420, protein: 16, carbs: 38, fat: 24, fiber: 1, sodium: 680 },
    allergens: ['dairy', 'gluten', 'eggs'], tags: ['tapas', 'frito'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-005', name: 'Fabada Asturiana', category: 'dinner', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Pon las alubias a remojo la noche anterior.', 'Escurre las alubias y ponlas en una cazuela con agua fría.', 'Añade el chorizo, la morcilla y el lacón.', 'Cocina a fuego lento 2 horas añadiendo agua fría de vez en cuando.', 'Sazona al final con sal y azafrán.', 'Sirve con un buen pan de pueblo.'],
    ingredients: [
      { name: 'Alubias blancas', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Chorizo', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Morcilla', quantity: 150, unit: 'g', isAllergen: false },
      { name: 'Lacón', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Azafrán', quantity: 1, unit: 'g', isAllergen: false },
      { name: 'Sal', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 20, cookTime: 120, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 580, protein: 38, carbs: 52, fat: 22, fiber: 12, sodium: 820 },
    allergens: [], tags: ['legumbres', 'contundente', 'invierno'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA ITALIANA =====
  {
    id: 'seed-006', name: 'Pasta Carbonara', category: 'dinner', cuisine: 'Italian', cuisineFlag: '🇮🇹',
    instructions: ['Cuece los espaguetis al dente en agua con sal.', 'Mientras tanto, fríe la panceta hasta que esté crujiente.', 'Bate los huevos con el queso parmesano y pimienta negra.', 'Escurre la pasta reservando un poco de agua de cocción.', 'Mezcla la pasta caliente con la panceta fuera del fuego.', 'Añade la mezcla de huevo y queso removiendo rápidamente.', 'Añade agua de cocción si es necesario para ligar la salsa.'],
    ingredients: [
      { name: 'Espaguetis', quantity: 400, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Panceta', quantity: 150, unit: 'g', isAllergen: false },
      { name: 'Huevos', quantity: 4, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Queso parmesano', quantity: 80, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Pimienta negra', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Sal', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 10, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 550, protein: 26, carbs: 62, fat: 22, fiber: 3, sodium: 520 },
    allergens: ['gluten', 'eggs', 'dairy'], tags: ['pasta', 'italiano'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-007', name: 'Pizza Margarita', category: 'dinner', cuisine: 'Italian', cuisineFlag: '🇮🇹',
    instructions: ['Disuelve la levadura en agua tibia con una pizca de azúcar.', 'Mezcla la harina con sal, añade la levadura y el aceite.', 'Amasa 10 min hasta obtener una masa lisa. Deja reposar 1 hora.', 'Estira la masa sobre papel de hornear.', 'Extiende el tomate, añade la mozzarella cortada.', 'Hornea a 220°C durante 12-15 min.', 'Añade hojas de albahaca fresca al sacar del horno.'],
    ingredients: [
      { name: 'Harina de fuerza', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Levadura fresca', quantity: 10, unit: 'g', isAllergen: false },
      { name: 'Tomate triturado', quantity: 200, unit: 'ml', isAllergen: false },
      { name: 'Mozzarella', quantity: 200, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Albahaca fresca', quantity: 10, unit: 'g', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml', isAllergen: false },
    ],
    prepTime: 20, cookTime: 15, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 480, protein: 18, carbs: 65, fat: 16, fiber: 4, sodium: 580 },
    allergens: ['gluten', 'dairy'], tags: ['pizza', 'vegetariano'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-008', name: 'Risotto al Funghi', category: 'dinner', cuisine: 'Italian', cuisineFlag: '🇮🇹',
    instructions: ['Hidrata las setas en agua tibia 20 min.', 'Sofríe la cebolla en aceite hasta que esté transparente.', 'Añade el arroz y tuéstalo 2 min.', 'Incorpora el vino blanco y deja evaporar.', 'Añade el caldo caliente cucharón a cucharón removiendo constantemente.', 'Incorpora las setas y el queso parmesano.', 'Rectifica de sal y sirve inmediatamente.'],
    ingredients: [
      { name: 'Arroz para risotto (Arborio)', quantity: 320, unit: 'g', isAllergen: false },
      { name: 'Setas variadas', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Vino blanco', quantity: 100, unit: 'ml', isAllergen: false },
      { name: 'Caldo de verduras', quantity: 1000, unit: 'ml', isAllergen: false },
      { name: 'Queso parmesano', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Mantequilla', quantity: 30, unit: 'g', isAllergen: true, allergenType: 'dairy' },
    ],
    prepTime: 15, cookTime: 30, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/c18lqy1574260036.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 420, protein: 12, carbs: 68, fat: 10, fiber: 2, sodium: 380 },
    allergens: ['dairy'], tags: ['arroz', 'vegetariano'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA FRANCESA =====
  {
    id: 'seed-009', name: 'Ratatouille Provenzal', category: 'dinner', cuisine: 'French', cuisineFlag: '🇫🇷',
    instructions: ['Corta todos los vegetales en rodajas finas.', 'Sofríe la cebolla y el ajo en aceite de oliva.', 'Añade el tomate triturado y las hierbas provenzales.', 'Dispón las rodajas de vegetales en círculos sobre la salsa.', 'Rocía con aceite de oliva y hornea a 180°C durante 45 min.', 'Sirve caliente o a temperatura ambiente.'],
    ingredients: [
      { name: 'Berenjena', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Calabacín', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Pimiento rojo', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Tomate', quantity: 4, unit: 'unidades', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Ajo', quantity: 3, unit: 'dientes', isAllergen: false },
      { name: 'Hierbas provenzales', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
    ],
    prepTime: 20, cookTime: 45, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 180, protein: 4, carbs: 22, fat: 9, fiber: 7, sodium: 220 },
    allergens: [], tags: ['vegetariano', 'vegano', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-010', name: 'Quiche Lorraine', category: 'lunch', cuisine: 'French', cuisineFlag: '🇫🇷',
    instructions: ['Extiende la masa quebrada en un molde y pincha con un tenedor.', 'Hornea en blanco 10 min a 180°C.', 'Mezcla los huevos, la nata, la sal y la nuez moscada.', 'Añade la panceta frita y el queso rallado.', 'Vierte sobre la masa precocida.', 'Hornea 30-35 min hasta que cuaje y dore.', 'Deja templar antes de servir.'],
    ingredients: [
      { name: 'Masa quebrada', quantity: 1, unit: 'lámina', isAllergen: true, allergenType: 'gluten' },
      { name: 'Panceta', quantity: 150, unit: 'g', isAllergen: false },
      { name: 'Huevos', quantity: 3, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Nata para cocinar', quantity: 200, unit: 'ml', isAllergen: true, allergenType: 'dairy' },
      { name: 'Queso gruyère rallado', quantity: 100, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Nuez moscada', quantity: 1, unit: 'pizca', isAllergen: false },
    ],
    prepTime: 15, cookTime: 45, servings: 6,
    imageUrl: 'https://www.themealdb.com/images/media/meals/xqrwsp1511628893.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 460, protein: 18, carbs: 28, fat: 32, fiber: 1, sodium: 560 },
    allergens: ['gluten', 'eggs', 'dairy'], tags: ['tartaleta', 'francés'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA GRIEGA =====
  {
    id: 'seed-011', name: 'Moussaka Griega', category: 'dinner', cuisine: 'Greek', cuisineFlag: '🇬🇷',
    instructions: ['Corta las berenjenas y fríelas ligeramente.', 'Prepara un sofrito con la cebolla, el ajo y la carne picada.', 'Añade el tomate, la canela y la nuez moscada.', 'Prepara una bechamel espesa.', 'Monta en capas: berenjena, carne, berenjena, bechamel.', 'Hornea a 180°C durante 45 min.', 'Deja reposar 10 min antes de cortar.'],
    ingredients: [
      { name: 'Berenjena', quantity: 3, unit: 'unidades', isAllergen: false },
      { name: 'Carne picada de cordero', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Tomate triturado', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Leche', quantity: 500, unit: 'ml', isAllergen: true, allergenType: 'dairy' },
      { name: 'Harina', quantity: 50, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Mantequilla', quantity: 50, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Huevo', quantity: 1, unit: 'unidad', isAllergen: true, allergenType: 'eggs' },
      { name: 'Canela', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 30, cookTime: 60, servings: 6,
    imageUrl: 'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 490, protein: 28, carbs: 28, fat: 30, fiber: 5, sodium: 480 },
    allergens: ['dairy', 'gluten', 'eggs'], tags: ['griego', 'cordero'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-012', name: 'Ensalada Griega', category: 'lunch', cuisine: 'Greek', cuisineFlag: '🇬🇷',
    instructions: ['Corta el tomate en gajos y el pepino en rodajas.', 'Añade la cebolla cortada en aros, el pimiento y las aceitunas.', 'Coloca el queso feta encima.', 'Aliña con aceite de oliva, orégano y sal.'],
    ingredients: [
      { name: 'Tomate', quantity: 3, unit: 'unidades', isAllergen: false },
      { name: 'Pepino', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Cebolla roja', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Queso feta', quantity: 200, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Aceitunas negras', quantity: 50, unit: 'g', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
      { name: 'Orégano', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/v3x2271699013358.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 280, protein: 10, carbs: 14, fat: 22, fiber: 4, sodium: 620 },
    allergens: ['dairy'], tags: ['ensalada', 'vegetariano', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA JAPONESA =====
  {
    id: 'seed-013', name: 'Salmón Teriyaki', category: 'dinner', cuisine: 'Japanese', cuisineFlag: '🇯🇵',
    instructions: ['Mezcla la salsa de soja, el mirin, el sake y el azúcar para la salsa teriyaki.', 'Marina el salmón 20 minutos en la salsa.', 'Calienta una sartén y cocina el salmón 3-4 min por lado.', 'Glasea con el resto de la marinada durante el último minuto.', 'Sirve con arroz blanco y sésamo.'],
    ingredients: [
      { name: 'Salmón en lomo', quantity: 500, unit: 'g', isAllergen: true, allergenType: 'fish' },
      { name: 'Salsa de soja', quantity: 60, unit: 'ml', isAllergen: true, allergenType: 'soybeans' },
      { name: 'Mirin', quantity: 30, unit: 'ml', isAllergen: false },
      { name: 'Sake', quantity: 30, unit: 'ml', isAllergen: false },
      { name: 'Azúcar', quantity: 15, unit: 'g', isAllergen: false },
      { name: 'Semillas de sésamo', quantity: 10, unit: 'g', isAllergen: true, allergenType: 'sesame' },
      { name: 'Arroz blanco', quantity: 300, unit: 'g', isAllergen: false },
    ],
    prepTime: 25, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 420, protein: 36, carbs: 42, fat: 12, fiber: 1, sodium: 920 },
    allergens: ['fish', 'soybeans', 'sesame'], tags: ['japonés', 'pescado', 'sin gluten'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-014', name: 'Miso Ramen', category: 'dinner', cuisine: 'Japanese', cuisineFlag: '🇯🇵',
    instructions: ['Prepara el caldo con agua, pasta miso, salsa de soja y caldo de pollo.', 'Cuece los fideos ramen según el paquete.', 'Sofríe el cerdo con ajo y jengibre.', 'Sirve el caldo caliente con los fideos, el cerdo, el huevo y los tropezones.'],
    ingredients: [
      { name: 'Fideos ramen', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Pasta miso', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'soybeans' },
      { name: 'Carne de cerdo', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Huevo', quantity: 4, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Maíz dulce', quantity: 100, unit: 'g', isAllergen: false },
      { name: 'Algas nori', quantity: 4, unit: 'láminas', isAllergen: false },
      { name: 'Caldo de pollo', quantity: 1200, unit: 'ml', isAllergen: false },
    ],
    prepTime: 20, cookTime: 30, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/w8uyff1490476268.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 480, protein: 28, carbs: 55, fat: 16, fiber: 3, sodium: 1200 },
    allergens: ['gluten', 'soybeans', 'eggs'], tags: ['sopa', 'japonés'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA CHINA =====
  {
    id: 'seed-015', name: 'Pollo con Verduras al Wok', category: 'dinner', cuisine: 'Chinese', cuisineFlag: '🇨🇳',
    instructions: ['Corta el pollo en trozos y marina con salsa de soja y maicena.', 'Calienta el wok a fuego muy alto.', 'Sofríe el ajo y el jengibre 30 segundos.', 'Añade el pollo y saltea 4 min.', 'Incorpora las verduras y saltea 3 min.', 'Añade la salsa de ostras y mezcla bien.', 'Sirve con arroz blanco.'],
    ingredients: [
      { name: 'Pechuga de pollo', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Brócoli', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Zanahoria', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Salsa de soja', quantity: 60, unit: 'ml', isAllergen: true, allergenType: 'soybeans' },
      { name: 'Salsa de ostras', quantity: 30, unit: 'ml', isAllergen: true, allergenType: 'molluscs' },
      { name: 'Jengibre', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Ajo', quantity: 3, unit: 'dientes', isAllergen: false },
      { name: 'Maicena', quantity: 15, unit: 'g', isAllergen: false },
    ],
    prepTime: 20, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/1529444830.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 320, protein: 34, carbs: 24, fat: 8, fiber: 5, sodium: 780 },
    allergens: ['soybeans', 'molluscs'], tags: ['chino', 'wok', 'sin gluten'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA INDIA =====
  {
    id: 'seed-016', name: 'Pollo Tikka Masala', category: 'dinner', cuisine: 'Indian', cuisineFlag: '🇮🇳',
    instructions: ['Trocea el pollo y marina con yogur, especias y zumo de limón al menos 2 horas.', 'Asa el pollo en el horno a 220°C durante 15 min.', 'Sofríe la cebolla, el ajo y el jengibre.', 'Añade el tomate, el garam masala, el comino y la cúrcuma.', 'Incorpora el pollo asado y la nata de coco.', 'Cocina 15 min a fuego lento.', 'Sirve con arroz basmati y cilantro fresco.'],
    ingredients: [
      { name: 'Pechuga de pollo', quantity: 600, unit: 'g', isAllergen: false },
      { name: 'Yogur natural', quantity: 150, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Tomate triturado', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Nata de coco', quantity: 200, unit: 'ml', isAllergen: false },
      { name: 'Garam masala', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Cúrcuma', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Arroz basmati', quantity: 300, unit: 'g', isAllergen: false },
    ],
    prepTime: 30, cookTime: 35, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/uktytv1511637710.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 450, protein: 38, carbs: 42, fat: 16, fiber: 4, sodium: 560 },
    allergens: ['dairy'], tags: ['indio', 'picante', 'sin gluten'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-017', name: 'Dal de Lentejas', category: 'dinner', cuisine: 'Indian', cuisineFlag: '🇮🇳',
    instructions: ['Lava las lentejas y cocínalas con agua hasta que estén tiernas.', 'Sofríe la cebolla, el ajo y el jengibre en aceite.', 'Añade los tomates y las especias.', 'Mezcla con las lentejas cocidas.', 'Cocina 10 min más a fuego lento.', 'Sirve con arroz o naan.'],
    ingredients: [
      { name: 'Lentejas rojas', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Cebolla', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Tomate', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Comino', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Cúrcuma', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Aceite de girasol', quantity: 30, unit: 'ml', isAllergen: false },
    ],
    prepTime: 10, cookTime: 30, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/vptwyt1511898809.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 280, protein: 18, carbs: 42, fat: 5, fiber: 14, sodium: 280 },
    allergens: [], tags: ['vegano', 'legumbres', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA MEXICANA =====
  {
    id: 'seed-018', name: 'Tacos de Pollo', category: 'dinner', cuisine: 'Mexican', cuisineFlag: '🇲🇽',
    instructions: ['Marina el pollo con especias, zumo de limón y ajo durante 30 min.', 'Asa el pollo a la plancha hasta que esté cocinado.', 'Deja reposar y desmenúzalo.', 'Calienta las tortillas.', 'Sirve el pollo en las tortillas con guacamole, cilantro y cebolla.'],
    ingredients: [
      { name: 'Pechuga de pollo', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Tortillas de maíz', quantity: 8, unit: 'unidades', isAllergen: false },
      { name: 'Aguacate', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Cilantro', quantity: 20, unit: 'g', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Limón', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Comino', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Pimentón ahumado', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 35, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/ryppsv1511815505.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 30, carbs: 38, fat: 12, fiber: 6, sodium: 420 },
    allergens: [], tags: ['mexicano', 'tacos', 'sin gluten'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-019', name: 'Guacamole', category: 'lunch', cuisine: 'Mexican', cuisineFlag: '🇲🇽',
    instructions: ['Aplasta los aguacates en un bol con un tenedor.', 'Añade el tomate picado, la cebolla, el jalapeño y el cilantro.', 'Sazona con zumo de limón y sal.', 'Sirve inmediatamente con nachos.'],
    ingredients: [
      { name: 'Aguacate', quantity: 3, unit: 'unidades', isAllergen: false },
      { name: 'Tomate', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Cebolla roja', quantity: 0.5, unit: 'unidad', isAllergen: false },
      { name: 'Jalapeño', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Cilantro fresco', quantity: 15, unit: 'g', isAllergen: false },
      { name: 'Limón', quantity: 1, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 10, cookTime: 0, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/kcv6hj1598733389.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 160, protein: 2, carbs: 8, fat: 14, fiber: 6, sodium: 120 },
    allergens: [], tags: ['vegano', 'sin gluten', 'snack'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA AMERICANA =====
  {
    id: 'seed-020', name: 'Hamburguesa Clásica', category: 'dinner', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Mezcla la carne picada con sal, pimienta y ajo en polvo.', 'Forma hamburguesas de 150g y hazles un hueco en el centro.', 'Asa a la plancha 4 min por lado a fuego alto.', 'Tuesta el pan durante el último minuto.', 'Monta la hamburguesa con la carne, lechuga, tomate, cebolla y salsas.'],
    ingredients: [
      { name: 'Carne picada de vacuno', quantity: 600, unit: 'g', isAllergen: false },
      { name: 'Pan de hamburguesa', quantity: 4, unit: 'unidades', isAllergen: true, allergenType: 'gluten' },
      { name: 'Lechuga', quantity: 4, unit: 'hojas', isAllergen: false },
      { name: 'Tomate', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Queso cheddar', quantity: 4, unit: 'lonchas', isAllergen: true, allergenType: 'dairy' },
      { name: 'Pepinillo', quantity: 4, unit: 'unidades', isAllergen: false },
    ],
    prepTime: 15, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 580, protein: 38, carbs: 38, fat: 30, fiber: 3, sodium: 780 },
    allergens: ['gluten', 'dairy'], tags: ['americano', 'hamburguesa'], nutriscore: 'D', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA MARROQUÍ =====
  {
    id: 'seed-021', name: 'Cuscús con Verduras', category: 'dinner', cuisine: 'Moroccan', cuisineFlag: '🇲🇦',
    instructions: ['Hidrata el cuscús con caldo caliente y aceite de oliva. Tapa 5 min.', 'Sofríe la cebolla y el ajo con las especias.', 'Añade las verduras y el caldo.', 'Cocina 20 min.', 'Esponja el cuscús con un tenedor y sirve con las verduras encima.'],
    ingredients: [
      { name: 'Cuscús', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Garbanzos cocidos', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Calabaza', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Zanahoria', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Ras el hanout', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Canela', quantity: 0.5, unit: 'cdta', isAllergen: false },
      { name: 'Caldo de verduras', quantity: 500, unit: 'ml', isAllergen: false },
    ],
    prepTime: 15, cookTime: 25, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/u3tgir1583268248.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 14, carbs: 68, fat: 6, fiber: 10, sodium: 320 },
    allergens: ['gluten'], tags: ['vegetariano', 'marroquí'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA TURCA =====
  {
    id: 'seed-022', name: 'Doner Kebab Casero', category: 'dinner', cuisine: 'Turkish', cuisineFlag: '🇹🇷',
    instructions: ['Marina la carne con yogur, especias y ajo durante 4 horas.', 'Asa la carne en brochetas.', 'Corta en láminas finas.', 'Sirve en pan pita con lechuga, tomate y salsa de yogur.'],
    ingredients: [
      { name: 'Carne de cordero', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Yogur natural', quantity: 100, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Pan pita', quantity: 4, unit: 'unidades', isAllergen: true, allergenType: 'gluten' },
      { name: 'Comino', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Pimentón', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Ajo', quantity: 3, unit: 'dientes', isAllergen: false },
      { name: 'Lechuga', quantity: 1, unit: 'puñado', isAllergen: false },
    ],
    prepTime: 240, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/k420tj1585565244.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 480, protein: 36, carbs: 38, fat: 20, fiber: 3, sodium: 560 },
    allergens: ['dairy', 'gluten'], tags: ['turco', 'cordero'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== COCINA TAILANDESA =====
  {
    id: 'seed-023', name: 'Pad Thai', category: 'dinner', cuisine: 'Thai', cuisineFlag: '🇹🇭',
    instructions: ['Remoja los fideos de arroz en agua tibia 20 min.', 'Calienta el wok y sofríe el ajo y las gambas.', 'Añade los fideos escurridos y saltea.', 'Empuja a un lado y scramble los huevos.', 'Añade la salsa de tamarindo, salsa de pescado y azúcar.', 'Mezcla todo y sirve con cacahuetes, brotes y lima.'],
    ingredients: [
      { name: 'Fideos de arroz', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Gambas peladas', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'crustaceans' },
      { name: 'Huevos', quantity: 3, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Salsa de tamarindo', quantity: 60, unit: 'ml', isAllergen: false },
      { name: 'Salsa de pescado', quantity: 30, unit: 'ml', isAllergen: true, allergenType: 'fish' },
      { name: 'Cacahuetes', quantity: 50, unit: 'g', isAllergen: true, allergenType: 'peanuts' },
      { name: 'Brotes de soja', quantity: 100, unit: 'g', isAllergen: true, allergenType: 'soybeans' },
    ],
    prepTime: 30, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 420, protein: 24, carbs: 58, fat: 10, fiber: 4, sodium: 860 },
    allergens: ['crustaceans', 'eggs', 'fish', 'peanuts', 'soybeans'], tags: ['tailandés', 'fideos'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== MÁS RECETAS MEDITERRÁNEAS =====
  {
    id: 'seed-024', name: 'Hummus Casero', category: 'lunch', cuisine: 'Greek', cuisineFlag: '🇬🇷',
    instructions: ['Escurre y enjuaga los garbanzos.', 'Tritura con el tahini, zumo de limón, ajo y sal.', 'Añade agua poco a poco hasta obtener la textura deseada.', 'Sirve con aceite de oliva, pimentón y pan de pita.'],
    ingredients: [
      { name: 'Garbanzos cocidos', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Tahini (pasta de sésamo)', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'sesame' },
      { name: 'Limón', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Ajo', quantity: 2, unit: 'dientes', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
      { name: 'Comino', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 10, cookTime: 0, servings: 6,
    imageUrl: 'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 200, protein: 7, carbs: 20, fat: 11, fiber: 5, sodium: 280 },
    allergens: ['sesame'], tags: ['vegano', 'sin gluten', 'aperitivo'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-025', name: 'Sopa de Lentejas', category: 'dinner', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Sofríe la cebolla, el ajo y las zanahorias.', 'Añade las lentejas, el tomate y las especias.', 'Cubre con caldo y cocina 30 min.', 'Ajusta la consistencia y sazona.', 'Sirve con pan crujiente.'],
    ingredients: [
      { name: 'Lentejas pardinas', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Zanahoria', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Tomate triturado', quantity: 200, unit: 'ml', isAllergen: false },
      { name: 'Chorizo', quantity: 100, unit: 'g', isAllergen: false },
      { name: 'Pimentón', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Caldo de verduras', quantity: 1000, unit: 'ml', isAllergen: false },
    ],
    prepTime: 10, cookTime: 35, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wrdsvt1511556563.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 310, protein: 18, carbs: 46, fat: 6, fiber: 12, sodium: 480 },
    allergens: [], tags: ['legumbres', 'invierno', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== DESAYUNOS =====
  {
    id: 'seed-026', name: 'Avena con Frutas', category: 'breakfast', cuisine: 'British', cuisineFlag: '🇬🇧',
    instructions: ['Calienta la leche o agua a fuego medio.', 'Añade los copos de avena y cocina 5 min removiendo.', 'Sirve con frutas frescas, miel y frutos secos.'],
    ingredients: [
      { name: 'Copos de avena', quantity: 80, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Leche vegetal', quantity: 250, unit: 'ml', isAllergen: false },
      { name: 'Plátano', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Frutos rojos', quantity: 50, unit: 'g', isAllergen: false },
      { name: 'Miel', quantity: 1, unit: 'cda', isAllergen: false },
      { name: 'Nueces', quantity: 20, unit: 'g', isAllergen: true, allergenType: 'nuts' },
    ],
    prepTime: 5, cookTime: 10, servings: 1,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wtqixi1511827174.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 11, carbs: 62, fat: 10, fiber: 7, sodium: 80 },
    allergens: ['gluten', 'nuts'], tags: ['desayuno', 'saludable'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-027', name: 'Tostadas con Aguacate', category: 'breakfast', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Tuesta el pan.', 'Aplasta el aguacate con zumo de limón y sal.', 'Extiende sobre las tostadas.', 'Añade el huevo pochado y los tomates cherry.', 'Espolvorea con pimienta roja y semillas de sésamo.'],
    ingredients: [
      { name: 'Pan integral', quantity: 2, unit: 'rebanadas', isAllergen: true, allergenType: 'gluten' },
      { name: 'Aguacate', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Huevo', quantity: 2, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Tomates cherry', quantity: 8, unit: 'unidades', isAllergen: false },
      { name: 'Limón', quantity: 0.5, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 10, cookTime: 5, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/eba655821511571535.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 320, protein: 13, carbs: 28, fat: 18, fiber: 8, sodium: 380 },
    allergens: ['gluten', 'eggs'], tags: ['desayuno', 'saludable'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== POSTRES =====
  {
    id: 'seed-028', name: 'Tarta de Manzana', category: 'dessert', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Precalienta el horno a 180°C.', 'Mezcla la harina, la mantequilla y el azúcar hasta obtener migas.', 'Presiona la mitad en el molde.', 'Mezcla las manzanas con azúcar, canela y maicena.', 'Coloca el relleno sobre la base.', 'Cubre con el resto de la masa.', 'Hornea 45 min hasta dorar.'],
    ingredients: [
      { name: 'Manzanas', quantity: 6, unit: 'unidades', isAllergen: false },
      { name: 'Harina', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Mantequilla', quantity: 150, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Azúcar', quantity: 150, unit: 'g', isAllergen: false },
      { name: 'Canela', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Maicena', quantity: 20, unit: 'g', isAllergen: false },
    ],
    prepTime: 20, cookTime: 45, servings: 8,
    imageUrl: 'https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 350, protein: 4, carbs: 52, fat: 14, fiber: 3, sodium: 180 },
    allergens: ['gluten', 'dairy'], tags: ['postre', 'tarta'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-029', name: 'Crema Catalana', category: 'dessert', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Calienta la leche con la canela y la piel de limón.', 'Bate las yemas con el azúcar y la maicena.', 'Añade la leche caliente a las yemas poco a poco.', 'Cocina a fuego lento removiendo hasta espesar.', 'Vierte en ramequines y deja enfriar.', 'Espolvorea azúcar y quema con soplete antes de servir.'],
    ingredients: [
      { name: 'Leche entera', quantity: 500, unit: 'ml', isAllergen: true, allergenType: 'dairy' },
      { name: 'Yemas de huevo', quantity: 4, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Azúcar', quantity: 100, unit: 'g', isAllergen: false },
      { name: 'Maicena', quantity: 20, unit: 'g', isAllergen: false },
      { name: 'Canela en rama', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Piel de limón', quantity: 1, unit: 'tira', isAllergen: false },
    ],
    prepTime: 15, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/v5c39k1571515610.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 240, protein: 7, carbs: 36, fat: 8, fiber: 0, sodium: 80 },
    allergens: ['dairy', 'eggs'], tags: ['postre', 'español', 'sin gluten'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-030', name: 'Tiramisú', category: 'dessert', cuisine: 'Italian', cuisineFlag: '🇮🇹',
    instructions: ['Bate el mascarpone con las yemas y el azúcar.', 'Monta las claras a punto de nieve e incorpora a la mezcla.', 'Empapa los bizcochos en café y dispón en una fuente.', 'Alterna capas de bizcocho y crema.', 'Espolvorea cacao en polvo y refrigera 4 horas.'],
    ingredients: [
      { name: 'Queso mascarpone', quantity: 250, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Huevos', quantity: 3, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Bizcochos de soletilla', quantity: 200, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Café expreso', quantity: 200, unit: 'ml', isAllergen: false },
      { name: 'Azúcar glas', quantity: 80, unit: 'g', isAllergen: false },
      { name: 'Cacao en polvo', quantity: 20, unit: 'g', isAllergen: false },
    ],
    prepTime: 30, cookTime: 0, servings: 6,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 8, carbs: 42, fat: 20, fiber: 1, sodium: 120 },
    allergens: ['dairy', 'eggs', 'gluten'], tags: ['postre', 'italiano', 'sin cocción'], nutriscore: 'D', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== MÁS RECETAS VARIADAS =====
  {
    id: 'seed-031', name: 'Pollo al Horno con Limón', category: 'dinner', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Precalienta el horno a 200°C.', 'Limpia el pollo y frótalo con ajo, romero y aceite.', 'Introduce limones cortados dentro del pollo.', 'Coloca en una bandeja con patatas y verduras.', 'Hornea 1h 20min hasta que esté dorado.', 'Deja reposar 10 min antes de servir.'],
    ingredients: [
      { name: 'Pollo entero', quantity: 1500, unit: 'g', isAllergen: false },
      { name: 'Limón', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Ajo', quantity: 6, unit: 'dientes', isAllergen: false },
      { name: 'Romero fresco', quantity: 2, unit: 'ramas', isAllergen: false },
      { name: 'Patatas', quantity: 600, unit: 'g', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
    ],
    prepTime: 20, cookTime: 80, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 420, protein: 42, carbs: 28, fat: 16, fiber: 3, sodium: 360 },
    allergens: [], tags: ['pollo', 'sin gluten', 'horno'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-032', name: 'Merluza en Salsa Verde', category: 'dinner', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Sofríe el ajo y la guindilla en aceite.', 'Añade el perejil picado y el caldo de pescado.', 'Incorpora los medallones de merluza.', 'Cocina 8-10 min a fuego medio-bajo.', 'Añade las almejas y cocina tapado hasta que se abran.'],
    ingredients: [
      { name: 'Merluza', quantity: 800, unit: 'g', isAllergen: true, allergenType: 'fish' },
      { name: 'Almejas', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'molluscs' },
      { name: 'Ajo', quantity: 4, unit: 'dientes', isAllergen: false },
      { name: 'Perejil', quantity: 30, unit: 'g', isAllergen: false },
      { name: 'Caldo de pescado', quantity: 200, unit: 'ml', isAllergen: true, allergenType: 'fish' },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
    ],
    prepTime: 15, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 280, protein: 40, carbs: 4, fat: 12, fiber: 1, sodium: 520 },
    allergens: ['fish', 'molluscs'], tags: ['pescado', 'sin gluten', 'español'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-033', name: 'Curry de Garbanzos', category: 'dinner', cuisine: 'Indian', cuisineFlag: '🇮🇳',
    instructions: ['Sofríe la cebolla con especias hasta dorar.', 'Añade el tomate triturado y cocina 5 min.', 'Incorpora los garbanzos y el caldo.', 'Cocina 20 min a fuego medio.', 'Ajusta especias y sirve con arroz.'],
    ingredients: [
      { name: 'Garbanzos cocidos', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Cebolla', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Tomate triturado', quantity: 400, unit: 'ml', isAllergen: false },
      { name: 'Garam masala', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Cúrcuma', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Comino', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Arroz basmati', quantity: 300, unit: 'g', isAllergen: false },
    ],
    prepTime: 10, cookTime: 25, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/spswqs1511558697.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 360, protein: 14, carbs: 58, fat: 7, fiber: 12, sodium: 380 },
    allergens: [], tags: ['vegano', 'sin gluten', 'indio'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-034', name: 'Salmón con Espinacas', category: 'dinner', cuisine: 'British', cuisineFlag: '🇬🇧',
    instructions: ['Sazona el salmón y séllalo en sartén 3 min por cada lado.', 'Saltea las espinacas con ajo.', 'Prepara la salsa con nata y limón.', 'Sirve el salmón sobre las espinacas con la salsa.'],
    ingredients: [
      { name: 'Salmón', quantity: 600, unit: 'g', isAllergen: true, allergenType: 'fish' },
      { name: 'Espinacas', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Nata', quantity: 100, unit: 'ml', isAllergen: true, allergenType: 'dairy' },
      { name: 'Ajo', quantity: 2, unit: 'dientes', isAllergen: false },
      { name: 'Limón', quantity: 1, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 10, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/hbxb771564839060.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 38, carbs: 4, fat: 24, fiber: 3, sodium: 380 },
    allergens: ['fish', 'dairy'], tags: ['pescado', 'sin gluten', 'omega3'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-035', name: 'Ensalada César', category: 'lunch', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Prepara la salsa mezclando mayonesa, parmesano, ajo y zumo de limón.', 'Corta la lechuga romana en trozos grandes.', 'Prepara los picatostes tostando pan con ajo.', 'Mezcla la lechuga con la salsa y los picatostes.', 'Añade el parmesano rallado por encima.'],
    ingredients: [
      { name: 'Lechuga romana', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Pan tostado', quantity: 100, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Queso parmesano', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Mayonesa', quantity: 80, unit: 'g', isAllergen: true, allergenType: 'eggs' },
      { name: 'Ajo', quantity: 1, unit: 'diente', isAllergen: false },
      { name: 'Limón', quantity: 1, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 15, cookTime: 5, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 340, protein: 12, carbs: 22, fat: 24, fiber: 4, sodium: 580 },
    allergens: ['gluten', 'dairy', 'eggs'], tags: ['ensalada', 'americano'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== RECETAS BRITÁNICAS =====
  {
    id: 'seed-036', name: 'Fish and Chips', category: 'dinner', cuisine: 'British', cuisineFlag: '🇬🇧',
    instructions: ['Prepara la masa con harina, levadura y cerveza.', 'Corta el bacalao en trozos y reboza en la masa.', 'Fríe en aceite a 180°C hasta dorar.', 'Fríe las patatas cortadas en bastones.', 'Sirve con vinagre de malta y salsa tartara.'],
    ingredients: [
      { name: 'Bacalao fresco', quantity: 600, unit: 'g', isAllergen: true, allergenType: 'fish' },
      { name: 'Harina', quantity: 150, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Cerveza', quantity: 200, unit: 'ml', isAllergen: true, allergenType: 'gluten' },
      { name: 'Patatas', quantity: 800, unit: 'g', isAllergen: false },
      { name: 'Aceite de girasol', quantity: 500, unit: 'ml', isAllergen: false },
    ],
    prepTime: 20, cookTime: 25, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/sywwyt1511889937.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 580, protein: 36, carbs: 60, fat: 22, fiber: 4, sodium: 480 },
    allergens: ['fish', 'gluten'], tags: ['británico', 'frito'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== RECETAS PERUANAS =====
  {
    id: 'seed-037', name: 'Ceviche de Gambas', category: 'lunch', cuisine: 'Peruvian', cuisineFlag: '🇵🇪',
    instructions: ['Pela y desveina las gambas.', 'Marina en zumo de lima 15 min.', 'Añade la cebolla roja, el ají y el cilantro.', 'Mezcla bien y ajusta la sal.', 'Sirve con maíz tostado y boniato cocido.'],
    ingredients: [
      { name: 'Gambas frescas', quantity: 500, unit: 'g', isAllergen: true, allergenType: 'crustaceans' },
      { name: 'Lima', quantity: 6, unit: 'unidades', isAllergen: false },
      { name: 'Cebolla roja', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Cilantro', quantity: 20, unit: 'g', isAllergen: false },
      { name: 'Ají amarillo', quantity: 1, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 20, cookTime: 0, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 160, protein: 22, carbs: 10, fat: 3, fiber: 2, sodium: 420 },
    allergens: ['crustaceans'], tags: ['peruano', 'sin gluten', 'sin cocción'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },

  // ===== MÁS RECETAS =====
  {
    id: 'seed-038', name: 'Pollo Teriyaki', category: 'dinner', cuisine: 'Japanese', cuisineFlag: '🇯🇵',
    instructions: ['Prepara salsa teriyaki con soja, mirin y azúcar.', 'Marina el pollo 30 min.', 'Asa en sartén 5 min por lado.', 'Glasea con más salsa al final.', 'Sirve con arroz y sésamo.'],
    ingredients: [
      { name: 'Muslos de pollo', quantity: 600, unit: 'g', isAllergen: false },
      { name: 'Salsa de soja', quantity: 60, unit: 'ml', isAllergen: true, allergenType: 'soybeans' },
      { name: 'Mirin', quantity: 30, unit: 'ml', isAllergen: false },
      { name: 'Azúcar moreno', quantity: 20, unit: 'g', isAllergen: false },
      { name: 'Sésamo', quantity: 10, unit: 'g', isAllergen: true, allergenType: 'sesame' },
    ],
    prepTime: 35, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 36, carbs: 18, fat: 16, fiber: 0, sodium: 780 },
    allergens: ['soybeans', 'sesame'], tags: ['japonés', 'sin gluten', 'pollo'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-039', name: 'Shakshuka', category: 'breakfast', cuisine: 'Moroccan', cuisineFlag: '🇲🇦',
    instructions: ['Sofríe la cebolla y el pimiento en aceite.', 'Añade el tomate, las especias y el harissa.', 'Cocina 10 min hasta reducir.', 'Haz 4 huecos y casca los huevos.', 'Tapa y cocina a fuego bajo 8 min.', 'Sirve con pan de pita.'],
    ingredients: [
      { name: 'Huevos', quantity: 4, unit: 'unidades', isAllergen: true, allergenType: 'eggs' },
      { name: 'Tomate triturado', quantity: 600, unit: 'ml', isAllergen: false },
      { name: 'Pimiento rojo', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Comino', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Pimentón', quantity: 1, unit: 'cdta', isAllergen: false },
    ],
    prepTime: 10, cookTime: 25, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/g373701551450225.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 200, protein: 12, carbs: 16, fat: 10, fiber: 4, sodium: 480 },
    allergens: ['eggs'], tags: ['desayuno', 'vegetariano', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-040', name: 'Pisto Manchego', category: 'lunch', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Sofríe la cebolla y el ajo en aceite.', 'Añade el pimiento en trozos y sofríe 5 min.', 'Incorpora la berenjena y el calabacín.', 'Añade el tomate y cocina 20 min.', 'Sazona y sirve con huevo frito o como acompañamiento.'],
    ingredients: [
      { name: 'Tomate', quantity: 400, unit: 'g', isAllergen: false },
      { name: 'Pimiento verde', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Berenjena', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Calabacín', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
    ],
    prepTime: 10, cookTime: 30, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 170, protein: 4, carbs: 18, fat: 10, fiber: 6, sodium: 180 },
    allergens: [], tags: ['vegetariano', 'vegano', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-041', name: 'Albóndigas en Salsa', category: 'dinner', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Mezcla la carne picada con huevo, ajo, perejil y pan rallado.', 'Forma las albóndigas y enharínalas.', 'Dóralas en aceite.', 'Prepara la salsa con tomate, cebolla y caldo.', 'Cocina las albóndigas en la salsa 20 min.'],
    ingredients: [
      { name: 'Carne picada mixta', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Huevo', quantity: 1, unit: 'unidad', isAllergen: true, allergenType: 'eggs' },
      { name: 'Pan rallado', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Tomate triturado', quantity: 400, unit: 'ml', isAllergen: false },
      { name: 'Cebolla', quantity: 1, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 20, cookTime: 30, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 430, protein: 30, carbs: 24, fat: 24, fiber: 3, sodium: 480 },
    allergens: ['eggs', 'gluten'], tags: ['español', 'carne'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-042', name: 'Ensalada de Quinoa', category: 'lunch', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Cuece la quinoa en agua el doble de su volumen.', 'Deja enfriar y mezcla con pepino, tomate y aguacate.', 'Aliña con zumo de limón, aceite y sal.', 'Añade semillas de girasol y hierbas frescas.'],
    ingredients: [
      { name: 'Quinoa', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Pepino', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Tomates cherry', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Aguacate', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Semillas de girasol', quantity: 30, unit: 'g', isAllergen: false },
      { name: 'Limón', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 40, unit: 'ml', isAllergen: false },
    ],
    prepTime: 10, cookTime: 15, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/vdwloy1713225718.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 320, protein: 10, carbs: 38, fat: 16, fiber: 8, sodium: 180 },
    allergens: [], tags: ['vegano', 'sin gluten', 'ensalada'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-043', name: 'Bacalao a la Vizcaína', category: 'dinner', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Desala el bacalao 48h cambiando el agua.', 'Prepara la salsa sofríendo cebolla, ajo y pimiento choricero.', 'Añade el tomate y caldo de pescado.', 'Cocina la salsa 20 min y tritura.', 'Fríe el bacalao y termina en la salsa 10 min.'],
    ingredients: [
      { name: 'Bacalao desalado', quantity: 700, unit: 'g', isAllergen: true, allergenType: 'fish' },
      { name: 'Pimiento choricero', quantity: 3, unit: 'unidades', isAllergen: false },
      { name: 'Cebolla', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Tomate', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Ajo', quantity: 4, unit: 'dientes', isAllergen: false },
    ],
    prepTime: 2880, cookTime: 40, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 300, protein: 42, carbs: 12, fat: 9, fiber: 2, sodium: 380 },
    allergens: ['fish'], tags: ['pescado', 'español', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-044', name: 'Lasaña Boloñesa', category: 'dinner', cuisine: 'Italian', cuisineFlag: '🇮🇹',
    instructions: ['Prepara la boloñesa con carne, tomate, vino y especias 45 min.', 'Prepara la bechamel.', 'Alterna capas de pasta, boloñesa y bechamel.', 'Finaliza con bechamel y queso.', 'Hornea 40 min a 180°C.'],
    ingredients: [
      { name: 'Láminas de lasaña', quantity: 12, unit: 'unidades', isAllergen: true, allergenType: 'gluten' },
      { name: 'Carne picada', quantity: 500, unit: 'g', isAllergen: false },
      { name: 'Tomate triturado', quantity: 400, unit: 'ml', isAllergen: false },
      { name: 'Leche', quantity: 500, unit: 'ml', isAllergen: true, allergenType: 'dairy' },
      { name: 'Harina', quantity: 50, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Queso mozzarella', quantity: 150, unit: 'g', isAllergen: true, allergenType: 'dairy' },
    ],
    prepTime: 30, cookTime: 90, servings: 6,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 520, protein: 28, carbs: 52, fat: 22, fiber: 4, sodium: 560 },
    allergens: ['gluten', 'dairy'], tags: ['pasta', 'italiano'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-045', name: 'Pollo Asado Marroquí', category: 'dinner', cuisine: 'Moroccan', cuisineFlag: '🇲🇦',
    instructions: ['Marina el pollo con chermoula (ajo, cilantro, comino, pimentón y aceite).', 'Deja marinar 2 horas.', 'Asa en horno a 200°C 50 min.', 'Sirve con cuscús y limón confitado.'],
    ingredients: [
      { name: 'Pollo', quantity: 1200, unit: 'g', isAllergen: false },
      { name: 'Cilantro', quantity: 20, unit: 'g', isAllergen: false },
      { name: 'Comino', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Pimentón', quantity: 2, unit: 'cdtas', isAllergen: false },
      { name: 'Ajo', quantity: 4, unit: 'dientes', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml', isAllergen: false },
      { name: 'Limón', quantity: 1, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 130, cookTime: 50, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 390, protein: 40, carbs: 6, fat: 22, fiber: 2, sodium: 380 },
    allergens: [], tags: ['marroquí', 'sin gluten', 'horno'], nutriscore: 'B', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-046', name: 'Bol de Açaí', category: 'breakfast', cuisine: 'Brazilian', cuisineFlag: '🇧🇷',
    instructions: ['Tritura el açaí congelado con leche vegetal.', 'Vierte en un bol.', 'Añade rodajas de plátano, frutos rojos y granola.', 'Rocía con miel.'],
    ingredients: [
      { name: 'Puré de açaí congelado', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Plátano', quantity: 2, unit: 'unidades', isAllergen: false },
      { name: 'Frutos rojos', quantity: 100, unit: 'g', isAllergen: false },
      { name: 'Granola', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'gluten' },
      { name: 'Miel', quantity: 1, unit: 'cda', isAllergen: false },
      { name: 'Leche de almendras', quantity: 100, unit: 'ml', isAllergen: true, allergenType: 'nuts' },
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/eba655821511571535.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 350, protein: 5, carbs: 62, fat: 10, fiber: 9, sodium: 60 },
    allergens: ['gluten', 'nuts'], tags: ['desayuno', 'saludable', 'tropical'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-047', name: 'Gyoza Japonesas', category: 'lunch', cuisine: 'Japanese', cuisineFlag: '🇯🇵',
    instructions: ['Mezcla cerdo picado con col, ajo, jengibre y salsa de soja.', 'Coloca la mezcla en los discos de masa.', 'Sella los bordes con agua.', 'Fríe 2 min, añade agua y tapa 5 min.', 'Sirve con salsa ponzu.'],
    ingredients: [
      { name: 'Discos de gyoza', quantity: 24, unit: 'unidades', isAllergen: true, allergenType: 'gluten' },
      { name: 'Carne de cerdo picada', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Col china', quantity: 200, unit: 'g', isAllergen: false },
      { name: 'Salsa de soja', quantity: 30, unit: 'ml', isAllergen: true, allergenType: 'soybeans' },
      { name: 'Jengibre', quantity: 10, unit: 'g', isAllergen: false },
      { name: 'Ajo', quantity: 2, unit: 'dientes', isAllergen: false },
    ],
    prepTime: 30, cookTime: 10, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/g373701551450225.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 320, protein: 18, carbs: 34, fat: 12, fiber: 2, sodium: 620 },
    allergens: ['gluten', 'soybeans'], tags: ['japonés', 'dumplings'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-048', name: 'Poke Bowl de Atún', category: 'lunch', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Corta el atún en dados y marina con salsa de soja y sésamo.', 'Prepara el arroz japonés.', 'Dispón en un bol el arroz, el atún y los toppings.', 'Aliña con salsa ponzu.'],
    ingredients: [
      { name: 'Atún fresco', quantity: 300, unit: 'g', isAllergen: true, allergenType: 'fish' },
      { name: 'Arroz japonés', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Aguacate', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Salsa de soja', quantity: 30, unit: 'ml', isAllergen: true, allergenType: 'soybeans' },
      { name: 'Sésamo tostado', quantity: 10, unit: 'g', isAllergen: true, allergenType: 'sesame' },
      { name: 'Pepino', quantity: 0.5, unit: 'unidad', isAllergen: false },
    ],
    prepTime: 20, cookTime: 20, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/vdwloy1713225718.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 450, protein: 32, carbs: 52, fat: 12, fiber: 4, sodium: 680 },
    allergens: ['fish', 'soybeans', 'sesame'], tags: ['poke', 'sin gluten', 'hawái'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-049', name: 'Patatas Bravas', category: 'lunch', cuisine: 'Spanish', cuisineFlag: '🇪🇸',
    instructions: ['Corta las patatas en dados y fríelas en aceite.', 'Prepara la salsa brava con tomate, pimentón picante y vinagre.', 'Sirve las patatas con la salsa y mayonesa de ajo.'],
    ingredients: [
      { name: 'Patatas', quantity: 800, unit: 'g', isAllergen: false },
      { name: 'Tomate triturado', quantity: 200, unit: 'ml', isAllergen: false },
      { name: 'Pimentón picante', quantity: 1, unit: 'cdta', isAllergen: false },
      { name: 'Vinagre', quantity: 1, unit: 'cda', isAllergen: false },
      { name: 'Aceite de oliva', quantity: 300, unit: 'ml', isAllergen: false },
      { name: 'Mayonesa', quantity: 60, unit: 'g', isAllergen: true, allergenType: 'eggs' },
      { name: 'Ajo', quantity: 2, unit: 'dientes', isAllergen: false },
    ],
    prepTime: 15, cookTime: 20, servings: 4,
    imageUrl: 'https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 380, protein: 5, carbs: 42, fat: 22, fiber: 4, sodium: 380 },
    allergens: ['eggs'], tags: ['tapas', 'vegetariano', 'español'], nutriscore: 'C', isFavorite: false, createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-050', name: 'Smoothie Bowl de Mango', category: 'breakfast', cuisine: 'American', cuisineFlag: '🇺🇸',
    instructions: ['Tritura el mango congelado con yogur.', 'Vierte en un bol.', 'Decora con fruta fresca, coco rallado y semillas de chía.'],
    ingredients: [
      { name: 'Mango congelado', quantity: 300, unit: 'g', isAllergen: false },
      { name: 'Yogur natural', quantity: 100, unit: 'g', isAllergen: true, allergenType: 'dairy' },
      { name: 'Kiwi', quantity: 1, unit: 'unidad', isAllergen: false },
      { name: 'Frutos rojos', quantity: 50, unit: 'g', isAllergen: false },
      { name: 'Coco rallado', quantity: 20, unit: 'g', isAllergen: false },
      { name: 'Semillas de chía', quantity: 10, unit: 'g', isAllergen: false },
    ],
    prepTime: 10, cookTime: 0, servings: 2,
    imageUrl: 'https://www.themealdb.com/images/media/meals/wtqixi1511827174.jpg',
    sourceApi: 'user_created', nutritionalInfo: { calories: 250, protein: 6, carbs: 48, fat: 5, fiber: 7, sodium: 40 },
    allergens: ['dairy'], tags: ['desayuno', 'tropical', 'sin gluten'], nutriscore: 'A', isFavorite: false, createdAt: now, updatedAt: now,
  },
]
